### ISSUE TITLE
No log files exist if the project path contains square brackets

### ISSUE THREAD

**Issue by EmadFathy** [opcodesio/log-viewer#115]
Hello,

The wrong behavior:
---------------------
When opening the log-viewer no log files exist.

The cause:
-----------
Using PHP glob() function to get the log files breaks the package if the project path contains **square brackets**. This is a known issue with glob() function (https://bugs.php.net/bug.php?id=33047).

Example path:
--------------
`D:\laravel\[2]New\`

Glob() is used here:
--------------------
https://github.com/opcodesio/log-viewer/blob/ba4a4936715e2251d7316a8e4800ed9e1ee76017/src/LogViewerService.php#L39

If you can  use another approach to get the log files, it will be great!

Specs:
------
PHP: 8.1.6
Laravel: 8.83.23
OS: Windows 10

**Comment by arukompas** [comment]
Hey! Thanks for the report!

Because it's a Window's specific issue/bug, and it only happens to very specific use cases (the chances of someone using brackets in folder names is very low), I consider this to be a low priority.

Also, I just don't know a way of fixing this without introducing breaking changes (such as switching to Symfony's Finder component).

If anyone has a fix for this, please contribute! :)

Thanks 🙏

**Comment by EmadFathy** [comment]
Hi @arukompas, thank you for the response.

At least you can check the path, and if it has the breaking symbols, show a user message telling the user that there is a problem with the path with the square bracket, maybe he is able to change it, but don't let him in the dark :).

**Comment by arukompas** [comment]
Good thought. If the squares can be seen in the value of `LogViewer::basePathForLogs()` then we can issue a warning/error. Otherwise, when adding additional glob patters to match directories **outside** of your laravel project - we won't be able to tell what we missed because of the square brackets.

I'll have a look at it this Friday :) Good suggestion!

**Comment by arukompas** [comment]
Hey @EmadFathy - the newest release `v1.5.1` should have a potential fix for the square brackets in Windows paths.

Let me know if it works or not! 😄

**Comment by EmadFathy** [comment]
Hi @arukompas ,

Thank you for your concern. I confirm version 1.5.3 (tested on Laravel 8.83.25 on Windows 10) is working perfectly with path including square brackets, and now the log files appears. thank you again.
