### ISSUE TITLE
Cannot view/select log files in Chrome (mobile)

### ISSUE THREAD

**Issue by nwaweru** [opcodesio/log-viewer#149]
Hi,

Awesome package, but I cannot use it on mobile (Chrome).

Only search works. No log files shown to select from, hence limiting viewing of my logs.

**Comment by Tiagospem** [comment]
same issue, on safari/chrome the log list doesn't appear

**Comment by jynxy** [comment]
for me the issue was as per the readme.

This is most often caused by your project being served from a sub-folder, like `example.com/your-laravel-project/log-viewer`.

Livewire by default tries to load its resources from the root of the domain, like `example.com/livewire/livewire.js`, but if that's outside your project's sub-folder, then you need to set a different asset_url. You can [read more about it here](https://laravel-livewire.com/docs/2.x/installation#configuring-the-asset-base-url).

Fortunately, the fix is easy:

1. Publish the Livewire config:
```shell
php artisan livewire:publish --config
```
2. Set the `asset_url` option in the `config/livewire.php` file to your app's subdomain:
```php
    'asset_url' => '/your-laravel-project',
```

**Comment by kamilberger18** [comment]
@jynxy I'm not sure if that's the case. My project is not served from sub-folder and I have the same problem. It appears only on Chrome browser. There are no entries in the console.
![log_viewer_no_sidebar](https://user-images.githubusercontent.com/28900188/208967109-94466658-7fe7-4d4c-8044-2aad1a815266.png)

**Comment by arukompas** [comment]
Sorry, but the v1 of the Log Viewer does not support mobile devices. It is planned to include it in the v2 some time this year.

Thanks for understanding!
