### ISSUE TITLE
No errors, but page does not format correctly

### ISSUE THREAD

**Issue by ksorbo** [opcodesio/log-viewer#268]
It looks as if both the app.js and the app.css are loading, but the page does not format correctly on initial load. The images are display full screen.
![logviewer2](https://github.com/opcodesio/log-viewer/assets/1436884/48e31967-8b66-41f4-b3c3-c2ee6f8904a4)

I have republished the assets (php artisan log-viewer:publish) several times, but it doesn't seem to make a difference.

Is there some way to completely refresh the assets? 

![logviewer](https://github.com/opcodesio/log-viewer/assets/1436884/4c1553f9-85ce-4509-abb4-6039b04b23b6)

**Comment by arukompas** [comment]
Hey @ksorbo it could also be errors in the console. Are there any? Perhaps the script fails to load.

Otherwise, you could try clearing `public/vendor/log-viewer` and then publishing again.

**Comment by ksorbo** [comment]
No errors in the browser console. Thanks. I will try to clear that folder..

**Comment by ksorbo** [comment]
Any other ideas?

I have cleared the public/vendor/log-viewer folder completely and then republished the assets.

I continue to get the same problem as posted above.

**Comment by ksorbo** [comment]
I upgraded to version 3.
Cleared the public/vendor/log-viewer
Published assets
Still get the same error.

**Comment by arukompas** [comment]
@ksorbo hey, How are you serving the app? Artisan serve, Valet, Xampp, something else?

Try a different serving method, like `php artisan serve` just to see if that fixes the issues. Perhaps the assets are not being served correctly.

**Comment by ksorbo** [comment]
I am having problems on my staging/production server. (When I serve on my development site using local windows machine using laravel homestead, it works ok.)

The server is using Ubuntu 22.10, php 8.1.7, apache2 2.4.54, laravel 10.19, log-viewer 3.1.3

I am getting 200 on all resources as shown in the attached graphic. When I open the js and css files, they both have full compressed content.

No errors showing in the console. I have manually cleared the /public/vendor/log-viewer folder and re published several times.

It seems like code is working correctly, **_but it looks as if the tailwind classes are not taking effect even though the css file is clearly loading (200)._**  Here is the css file that is loading:
https://staging2023.discipleshipdynamics.com/vendor/log-viewer/app.css?id=93151d8b186ef7758df8582425ff8082

You can see that tailwind is clearly loading. The class .w-5 is searchable in the css file. But when viewed in the inspector, the w-5 h-5 classes are not having any effect. 

The following is from my staging server. Debug-bar is also on this server. However, I am getting the same problem on the production server which does not have debug-bar present.
![image](https://github.com/opcodesio/log-viewer/assets/1436884/7669fb8e-7fbb-473f-8a2f-6e517f91ba77)

**Comment by arukompas** [comment]
@ksorbo we're getting closer! Thanks for the staging link, this helped me find something.

The file is being served as regular `text/html` content-type, which means although the browser receives it - it does not treat it like a CSS file. The same happens to the `app.js` file, which is why it's received but never loaded.

Have a look here:
<img width="988" alt="Screenshot 2023-09-23 at 09 47 40" src="https://github.com/opcodesio/log-viewer/assets/8697942/84172eb8-9712-4c69-9ffe-62aff07e9b79">

Something must be off with the way static assets are served on your staging/prod server. Please double-check your apache virtual host config, or the `.htaccess` file. I'm not exactly sure if there's anything in there that would change the content type of these files.

**Comment by MoatazAbdAlmageed** [comment]
I injected the css but got this >> 
<img width="1301" alt="image" src="https://github.com/opcodesio/log-viewer/assets/17373050/cbc2f640-b124-461e-aa6b-f92171b83b6e">

**Comment by MoatazAbdAlmageed** [comment]
> I injected the css but got this >> <img alt="image" width="1301" src="https://user-images.githubusercontent.com/17373050/284248183-cbc2f640-b124-461e-aa6b-f92171b83b6e.png">

I uses [stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha) to do that 
<img width="352" alt="image" src="https://github.com/opcodesio/log-viewer/assets/17373050/2ef4c89f-9678-484f-9a3c-00710dc1732f">

**Comment by MoatazAbdAlmageed** [comment]
> > I injected the css but got this >> <img alt="image" width="1301" src="https://user-images.githubusercontent.com/17373050/284248183-cbc2f640-b124-461e-aa6b-f92171b83b6e.png">
> 
> I uses [stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha) to do that <img alt="image" width="352" src="https://user-images.githubusercontent.com/17373050/284248356-2ef4c89f-9678-484f-9a3c-00710dc1732f.png">

now it's 
<img width="1033" alt="image" src="https://github.com/opcodesio/log-viewer/assets/17373050/46ed4ebf-84e3-48ce-bb98-0340553efa29">

**Comment by MoatazAbdAlmageed** [comment]
from firefox  I got this error 
<img width="911" alt="image" src="https://github.com/opcodesio/log-viewer/assets/17373050/afcf6edd-bbb5-4e19-8b0e-5a86296ea047">

**Comment by MoatazAbdAlmageed** [comment]
is this ok ?
<img width="1137" alt="image" src="https://github.com/opcodesio/log-viewer/assets/17373050/75c6f739-ebc6-40ca-8853-c79099bc5b3b">

**Comment by arukompas** [comment]
@MoatazAbdAlmageed , like mentioned in above comments, it's not ok that your CSS files are being served with content type of `text/plain`. The browser does not know it's a CSS file and thus it does not render it.

You probably have the same problem with the JS file - it should have the content type of `application/javascript` , otherwise the browser will not process it.

You should look at your server setup and how it serves static assets like JS and CSS.

**Comment by ksorbo** [comment]
I have confirmed that the problem was with my Apache server incorrectly serving the css files.

Thanks.
