### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by HUN-Sopheak** [opcodesio/log-viewer#338]
when data is null or empty string is not show you should be set default message " Null ".

**Comment by arukompas** [comment]
@HUN-Sopheak can you share the example log file and what it shows up in the frontend? Please provide as much as you can so I can replicate it.

**Comment by HUN-Sopheak** [comment]
I want to discuss an issue I encountered in the application's logging. I noticed that when there is an empty string or null value, it still stores the datetime in the storage/logs. Can you help me check this?
https://prnt.sc/6buWv80Suqh-
https://prnt.sc/bSY1nl4Z9wu3

**Comment by arukompas** [comment]
@HUN-Sopheak what is the expected result? If you log an empty value, it will be shown as empty in the log.

```php
Log::debug(null);
Log::debug('');
```
will both show up empty because they are empty.

As for the second screenshot, you can click on the log entry to expand it and show the full message/context. `array(` is just the first line of the log. The rest can be shown by expanding it.

**Comment by HUN-Sopheak** [comment]
ok i got it 
thank you sir
