### ISSUE TITLE
Does not load logs correctly when behind a load balancer

### ISSUE THREAD

**Issue by dewebdesigns** [opcodesio/log-viewer#65]
We have 3 instances setup on a load balancer. When we try to view the log files, they appear empty on some and after clicking a couple times it pulls up the right log based on the instance it's hitting - i'm guessing.

**Comment by arukompas** [comment]
Hey @dewebdesigns 

There are 2 problems in this case:
### 1. Logs are spread across multiple server instances

Currently, Log Viewer does not support loading logs from multiple server instances. It only loads the logs found on the same file system, locally. So if the load balancer routes the request to instance # 2, then it will returns logs found in the instance # 2.

It's not a feature that's currently prioritised and I don't think it will be any time soon.

### 2. Server is behind load balancer, thus it keeps switching to a different server instance

Luckily, this is meant to be fixed by Livewire (see https://github.com/livewire/livewire/pull/4354), so I don't think load balancers are the issue here. If you select to view the log file `laravel.log`, does every server instance have that file? And if so, does every file on each server instance have the same contents? Probably not. So if the load balancer keeps switching the requests to different server instances, then you'll keep getting different & inconsistent results.

Hope this explains why this is happening. Unfortunately, there isn't a quick fix at the moment, as the package simply does not support showing log files from multiple server instances :)
